services:
  document-merge-service:
    image: ghcr.io/adfinis/document-merge-service:dev
    build:
      context: .
      args:
        - ENV=dev
        - UID=$UID
        - VARIANT=full
    user: "${UID:?Set UID env variable to your user id}"
    volumes:
      - ./:/app
    command:
      [
        "/bin/sh",
        "-c",
        "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
      ]
    environment:
      - ENV=dev

  gotenberg:
    image: gotenberg/gotenberg:8-libreoffice@sha256:db97d06951a584d21cff7b44f5304e9f69c927dbcbc99d8e1c9ae38a60c5a4fd
    environment:
      - CHROMIUM_DISABLE_ROUTES=true
      - PDFENGINES_DISABLE_ROUTES=true
      - WEBHOOK_DISABLE=true
