services:
  document-merge-service:
    image: ghcr.io/adfinis/document-merge-service:dev
    build:
      context: .
      args:
        - ENV=dev
        - UID=$UID
        - VARIANT=full
    user: "${UID:?Set UID env variable to your user id}"
    volumes:
      - ./:/app
    command:
      [
        "/bin/sh",
        "-c",
        "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
      ]
    environment:
      - ENV=dev

  gotenberg:
    image: gotenberg/gotenberg:8-libreoffice@sha256:9c5ed0b83bd663bb76ca3ec16d3b40e44bb1de1e96897e6907a1ffa831966309
    environment:
      - CHROMIUM_DISABLE_ROUTES=true
      - PDFENGINES_DISABLE_ROUTES=true
      - WEBHOOK_DISABLE=true
