services:
  document-merge-service:
    image: ghcr.io/adfinis/document-merge-service:dev
    build:
      context: .
      args:
        - ENV=dev
        - UID=$UID
        - VARIANT=full
    user: "${UID:?Set UID env variable to your user id}"
    volumes:
      - ./:/app
    command:
      [
        "/bin/sh",
        "-c",
        "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
      ]
    environment:
      - ENV=dev

  gotenberg:
    image: gotenberg/gotenberg:8-libreoffice@sha256:3c23aeb3a027a63d7c71745fc9d83724bd58cf9dfa470396ac82c0896028db2a
    environment:
      - CHROMIUM_DISABLE_ROUTES=true
      - PDFENGINES_DISABLE_ROUTES=true
      - WEBHOOK_DISABLE=true
