# Generated by Django 2.2.16 on 2021-03-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_template_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="slug",
            field=models.SlugField(max_length=1048, primary_key=True, serialize=False),
        ),
    ]
