name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    env:
      ENV: dev
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Install poetry
        run: pipx install poetry
      - name: Setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --extras full --with dev
      - name: Run gitlint
        run: poetry run gitlint --contrib contrib-title-conventional-commits
      - name: Run ruff check
        run: poetry run ruff check .
      - name: Run mypy
        run: poetry run mypy document_merge_service
      - name: Run ruff format
        run: poetry run ruff format --check --diff .
      - name: Run migration check
        run: poetry run python manage.py makemigrations --check --dry-run --no-input

  docker-tests:
    name: Docker tests
    needs: [lint]
    runs-on: ubuntu-22.04
    env:
      ENV: dev
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      - name: Set UID
        run: |
          echo "UID=$(id --user)" > .env
      - name: Build docker containers
        run: docker compose up -d --build
      - name: Run pytest
        run: docker compose exec -T document-merge-service pytest --no-cov-on-fail --cov --create-db -vv

  compatibility-tests:
    name: Compatibility tests
    needs: [lint]
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        version:
          - "3.12"
          - "3.13"
          - "3.14"
        database:
          - "sqlite"
          - "postgres"
    services:
      postgres:
        image: postgres:alpine@sha256:54451ecb8ab38c24c3ec123f2fd501303a3a1856a5c66e98cecf2460d5e1e9d7
        env:
          POSTGRES_USER: document-merge-service
          POSTGRES_PASSWORD: document-merge-service
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      gotenberg:
        image: gotenberg/gotenberg:8-libreoffice@sha256:db97d06951a584d21cff7b44f5304e9f69c927dbcbc99d8e1c9ae38a60c5a4fd
        ports:
          - 3000:3000
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install poetry
        run: pipx install poetry
      - name: Setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.version }}
          cache: "poetry"
      - name: Prepare directories
        run: mkdir -p ${{ runner.temp }}/document-merge-service/data ${{ runner.temp }}/document-merge-service/media/attachments ${{ runner.temp }}/document-merge-service/media/__convert__
      - name: Install dependendies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends util-linux libmagic1 media-types
          poetry install --extras full --with dev
      - name: Set environment
        run: |
          echo "ENV=dev" >> .env
          echo "UID=$(id --user)" >> .env
          echo "DATABASE_DIR=${{ runner.temp }}/document-merge-service/data" >> .env
          echo "MEDIA_ROOT=${{ runner.temp }}/document-merge-service/media" >> .env
          echo "GOTENBERG_HOST=http://localhost" >> .env
      - name: Configure postgres
        if: ${{ matrix.database == 'postgres' }}
        run: |
          echo "DATABASE_ENGINE=django.db.backends.postgresql"
          echo "DATABASE_HOST=localhost"
          echo "DATABASE_PORT=5432"
          echo "DATABASE_NAME=document-merge-service"
          echo "DATABASE_USER=document-merge-service"
          echo "DATABASE_PASSWORD=document-merge-service"
      - name: Run tests
        run: poetry run pytest --no-cov-on-fail --cov --create-db -vv
